version: 1.0
publish: app
services:
  app:
    command: npm run start:dev && npm run start-server:dev
    build:
      type: dockerfile
      config: ./.runme/Dockerfile
    ports:
      - container: 8080
        public: 80